

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/GiftDB
#    username: root
#    password: Johnda12#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql


#    ?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false


##Amazon rds Connection

spring:
  datasource:
    url: jdbc:mysql://giftappdb.cjmwk0sx2jwt.eu-north-1.rds.amazonaws.com:3306/GiftDB
    username: root
    password: Johnda12#
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql


#microsoftSqlServer(Azure)


#
#spring:
#  datasource:
#    url: jdbc:sqlserver://giftdb.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: johnda
#    password: Giftdb12#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
#
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql



app:
  security:
    jwt:
      secretKey: 70337336763979244226452948404D635166546A576E5A7234743777217A2543
      expiration: 86400000       #a day
      refresh-token:
        expiration: 604800000     #seven days

  cloudinary:
    API_KEY: 662877474753217
    API_SECRET: F4lnVAARoy3IxOr-O6GyJbSNvhU
    CLOUD_NAME: jmnmumo







