
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/GiftDB
#    username: root
#    password: Johnda12#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.



spring:
  datasource:
    url: jdbc:mysql://giftappdb.cjmwk0sx2jwt.eu-north-1.rds.amazonaws.com:3306/GiftDB
    username: root
    password: Johnda12#
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

