#name: Springboot App of Gifts
#
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build-deploy:
#    strategy:
#      matrix:
#        retries: [ 1 ]
#    name  : build and deploy springboot app
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set Up Jdk 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: 17
#
#      - name: Unit Test code
#        run: mvn -B test --file pom.xml
#
#
#      - name: Build the application code
#        run: |
#          mvn clean
#          mvn -B test --file pom.xml
#
#      - name: clear docker cache
#        run: docker builder prune --force
#
#      - name: Clean Up Workspace
#        run: |
#          rm -rf /tmp/buildkit-mount*
#
#      - name: Build Docker Image
#        uses: docker/setup-buildx-action@v1
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/giftapp:latest
#
#      - name: Login to dockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{secrets.DOCKER_HUB_USERNAME}}
#          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
#
#      - name: push to dockerhub
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/giftapp:latest
#
#
#
#
#
#
#
#



name: Springboot App of Gifts

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    strategy:
      matrix:
        retries: [1]
    name: Build and deploy Spring Boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Test code
        run: mvn -B test --file pom.xml

      - name: Build the application code
        run: |
          mvn clean
          mvn -B test --file pom.xml

#      - name: Clear Docker Buildx Cache
#        run: docker builder prune --force
#
#      - name: Clean Up Workspace
#        run: |
#          rm -rf /tmp/buildkit-mount*

      - name: Get the date
        id: date
        run: echo "::set-output name=date::$(date +'%-m%d%H%M')"

#      - name: Build Docker Image
#        uses: docker/setup-buildx-action@v1
#        with:
#          context: .  # Verify that the build context is correct
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/giftapp:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .  # Verify that the build context is correct
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/giftapp:${{ steps.date.outputs.date }}
